// Command genairports converts the OurAirports dataset into a compact Go
// source file that gets compiled into the binary, so the app never needs
// network access to resolve an airport code.
//
// The source data is public domain, from
// https://github.com/davidmegginson/ourairports-data
//
//	go run ./cmd/genairports -in airports.csv -out internal/airports/data_gen.go
//
// Only large and medium airports that have an IATA code are kept, which is
// what a passenger ticket can actually name. That trims ~83,000 rows (mostly
// heliports, seaplane bases and private strips) down to a few thousand.
package main

import (
	"encoding/csv"
	"flag"
	"fmt"
	"io"
	"log"
	"os"
	"sort"
	"strconv"
	"strings"
)

// Column names are resolved from the header rather than hardcoded as indexes,
// so an upstream column reorder cannot silently shift latitude into longitude.
var wanted = []string{
	"type", "name", "latitude_deg", "longitude_deg",
	"iso_country", "municipality", "icao_code", "iata_code", "ident",
}

type airport struct {
	IATA, ICAO, Name, City, Country string
	Lat, Lon                        float64
}

func main() {
	in := flag.String("in", "airports.csv", "path to the OurAirports airports.csv")
	out := flag.String("out", "internal/airports/data_gen.go", "generated Go file to write")
	flag.Parse()

	f, err := os.Open(*in)
	if err != nil {
		log.Fatalf("open input: %v", err)
	}
	defer f.Close()

	r := csv.NewReader(f)
	r.FieldsPerRecord = -1
	header, err := r.Read()
	if err != nil {
		log.Fatalf("read header: %v", err)
	}
	col := map[string]int{}
	for i, h := range header {
		col[strings.TrimSpace(h)] = i
	}
	for _, w := range wanted {
		if _, ok := col[w]; !ok {
			log.Fatalf("input is missing the %q column; upstream format changed", w)
		}
	}
	get := func(rec []string, name string) string {
		i := col[name]
		if i >= len(rec) {
			return ""
		}
		return strings.TrimSpace(rec[i])
	}

	var airports []airport
	var scanned, skipped int
	for {
		rec, err := r.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			log.Fatalf("read row: %v", err)
		}
		scanned++

		switch get(rec, "type") {
		case "large_airport", "medium_airport":
		default:
			continue
		}
		iata := strings.ToUpper(get(rec, "iata_code"))
		if len(iata) != 3 {
			continue
		}
		lat, errLat := strconv.ParseFloat(get(rec, "latitude_deg"), 64)
		lon, errLon := strconv.ParseFloat(get(rec, "longitude_deg"), 64)
		if errLat != nil || errLon != nil ||
			lat < -90 || lat > 90 || lon < -180 || lon > 180 ||
			(lat == 0 && lon == 0) {
			skipped++
			continue
		}
		icao := strings.ToUpper(get(rec, "icao_code"))
		if icao == "" {
			// Older rows carry the ICAO identifier in `ident` instead.
			if id := strings.ToUpper(get(rec, "ident")); len(id) == 4 {
				icao = id
			}
		}
		airports = append(airports, airport{
			IATA:    iata,
			ICAO:    icao,
			Name:    clean(get(rec, "name")),
			City:    clean(get(rec, "municipality")),
			Country: strings.ToUpper(get(rec, "iso_country")),
			Lat:     lat,
			Lon:     lon,
		})
	}

	sort.Slice(airports, func(i, j int) bool { return airports[i].IATA < airports[j].IATA })

	// Records are packed into one tab/newline delimited string rather than a
	// map literal: it keeps the generated file small and compiles quickly.
	var blob strings.Builder
	for _, a := range airports {
		fmt.Fprintf(&blob, "%s\t%s\t%s\t%s\t%s\t%.6f\t%.6f\n",
			a.IATA, a.ICAO, a.Name, a.City, a.Country, a.Lat, a.Lon)
	}

	var src strings.Builder
	src.WriteString("// Code generated by cmd/genairports. DO NOT EDIT.\n")
	src.WriteString("//\n")
	src.WriteString("// Source: OurAirports (public domain),\n")
	src.WriteString("// https://github.com/davidmegginson/ourairports-data\n\n")
	src.WriteString("package airports\n\n")
	fmt.Fprintf(&src, "// count is the number of records packed into data.\nconst count = %d\n\n", len(airports))
	src.WriteString("// data holds one airport per line, tab separated:\n")
	src.WriteString("// IATA, ICAO, name, city, ISO country, latitude, longitude.\n")
	fmt.Fprintf(&src, "const data = %s\n", strconv.Quote(blob.String()))

	if err := os.WriteFile(*out, []byte(src.String()), 0o644); err != nil {
		log.Fatalf("write output: %v", err)
	}
	log.Printf("scanned %d rows, kept %d airports, skipped %d with unusable coordinates", scanned, len(airports), skipped)
	log.Printf("wrote %s (%.0f KB)", *out, float64(src.Len())/1024)
}

// clean strips the delimiters used by the packed format so a stray tab in an
// airport name cannot shift every following field.
func clean(s string) string {
	return strings.TrimSpace(strings.NewReplacer("\t", " ", "\n", " ", "\r", " ").Replace(s))
}
